In [1]:
# # Python Program for Floyd Warshall Algorithm 
# This code is contributed by Nikhil Kumar Singh(nickzuck_007) and modified by Zhenhui Peng (penguinzhou) to report the matrix in between

import numpy as np

  
# Define infinity as the large enough value. This value will be 
# used for vertices not connected to each other 
INF  = 99999
  
# Solves all pair shortest path via Floyd Warshall Algorithm 
def floydWarshall(graph): 
    # # Number of vertices in the graph 
    V = len(graph[0])
    """ dist[][] will be the output matrix that will finally 
        have the shortest distances between every pair of vertices """
    """ initializing the solution matrix same as input graph matrix 
    OR we can say that the initial values of shortest distances 
    are based on shortest paths considering no  
    intermediate vertices """
    dist = map(lambda i : map(lambda j : j , i) , graph) 
      
    """ Add all vertices one by one to the set of intermediate 
     vertices. 
     ---> Before start of an iteration, we have shortest distances 
     between all pairs of vertices such that the shortest 
     distances consider only the vertices in the set  
    {0, 1, 2, .. k-1} as intermediate vertices. 
      ----> After the end of a iteration, vertex no. k is 
     added to the set of intermediate vertices and the  
    set becomes {0, 1, 2, .. k} 
    """
    for k in range(V): 
  
        # pick all vertices as source one by one 
        for i in range(V): 
  
            # Pick all vertices as destination for the 
            # above picked source 
            for j in range(V): 

                # If vertex k is on the shortest path from  
                # i to j, then update the value of dist[i][j] 
                dist[i][j] = min(dist[i][j] , dist[i][k]+ dist[k][j]) 
        print("The %d th matrix" % (k+1))
        print(np.array(dist)) 
        
# A utility function to print the solution 
def printSolution(dist): 
    print("Following matrix shows the shortest distances between every pair of vertices") 
    for i in range(V): 
        for j in range(V): 
            if(dist[i][j] == INF): 
                print("%7s" %("INF"))
            else: 
                print("%7d\t" %(dist[i][j]))
            if j == V-1: 
                print("")

# Driver program to test the above program 
# Let us create the following weighted graph 
graph = [[0, INF, INF, INF, 7, INF, INF, 1, INF], 
         [INF, 0, INF, INF, INF, 7, INF, INF, 6], 
         [INF, -2, 0, INF, INF, INF, INF, INF, 9], 
         [-3, INF, INF, 0, INF, INF, INF, INF, 1], 
         [INF, 3, INF, INF, 0, INF, INF, INF, INF],
         [INF, INF, 4, INF, INF, 0, INF, INF, INF],
         [INF, INF, 5, -2, INF, INF, 0, INF, INF],
         [INF, INF, INF, 5, INF, INF, INF, 0, INF],
         [5, INF, INF, INF, -2, INF, 3, INF, 0]
        ] 
# Print the solution 
floydWarshall(graph); 
# Note: if the value of dist[i][j] is very large, then it is INF

The 1 th matrix
[[    0 99999 99999 99999     7 99999 99999     1 99999]
 [99999     0 99999 99999 99999     7 99999 99999     6]
 [99999    -2     0 99999 99999 99999 99999 99999     9]
 [   -3 99996 99996     0     4 99996 99996    -2     1]
 [99999     3 99999 99999     0 99999 99999 99999 99999]
 [99999 99999     4 99999 99999     0 99999 99999 99999]
 [99999 99999     5    -2 99999 99999     0 99999 99999]
 [99999 99999 99999     5 99999 99999 99999     0 99999]
 [    5 99999 99999 99999    -2 99999     3     6     0]]
The 2 th matrix
[[    0 99999 99999 99999     7 99999 99999     1 99999]
 [99999     0 99999 99999 99999     7 99999 99999     6]
 [99997    -2     0 99997 99997     5 99997 99997     4]
 [   -3 99996 99996     0     4 99996 99996    -2     1]
 [99999     3 99999 99999     0    10 99999 99999     9]
 [99999 99999     4 99999 99999     0 99999 99999 99999]
 [99999 99999     5    -2 99999 99999     0 99999 99999]
 [99999 99999 99999     5 99999 99999 99999     0 99999

In [2]:
# Python Program for divide-and-conqure dynamic programming method to solve all pairs shortest path problem
# This code is modified by Zhenhui Peng (penguinzhou) to deal with the 2nd dynamic programming method to solve all pairs shortest path problem
import numpy as np
import math
  
# Define infinity as the large enough value. This value will be 
# used for vertices not connected to each other 
INF  = 99999

dist_array = []
# Solves all pair shortest path via dcDP Algorithm 
def dcDP(graph): 
    # Number of vertices in the graph 
    V = len(graph[0])
    s = math.ceil(V**0.5)
    dist = map(lambda i : map(lambda j : j , i) , graph) 
    # Store the array in between
    dist_array.append(dist)
    for m in range(int(s)): 
        dist = dist_array[m]
        dist_new = np.zeros((V, V), dtype=np.int)
#         if 2^(m+1) > V:
#             break
        # pick all vertices as source one by one 
        for i in range(V): 
            # Pick all vertices as destination for the 
            # above picked source 
            for j in range(V): 
                dist_new[i][j] = INF
                for k in range(V): 
                    if (dist[i][k]+ dist[k][j]) < dist_new[i][j]:
                        dist_new[i][j] = dist[i][k]+ dist[k][j]
        dist_array.append(dist_new)
        print("The {} th matrix".format(2**(m+1)))
        print(dist_new)
  
  
# A utility function to print the solution 
def printSolution(dist): 
    print("Following matrix shows the shortest distances between every pair of vertices") 
    for i in range(V): 
        for j in range(V): 
            if(dist[i][j] == INF): 
                print("%7s" %("INF"))
            else: 
                print("%7d\t" %(dist[i][j]))
            if j == V-1: 
                print("")

# Driver program to test the above program 
# Let us create the following weighted graph 
graph = [[0, INF, INF, INF, 7, INF, INF, 1, INF], 
         [INF, 0, INF, INF, INF, 7, INF, INF, 6], 
         [INF, -2, 0, INF, INF, INF, INF, INF, 9], 
         [-3, INF, INF, 0, INF, INF, INF, INF, 1], 
         [INF, 3, INF, INF, 0, INF, INF, INF, INF],
         [INF, INF, 4, INF, INF, 0, INF, INF, INF],
         [INF, INF, 5, -2, INF, INF, 0, INF, INF],
         [INF, INF, INF, 5, INF, INF, INF, 0, INF],
         [5, INF, INF, INF, -2, INF, 3, INF, 0]
        ] 
# Print the solution 
dcDP(graph); 
# This code is contributed by Nikhil Kumar Singh(nickzuck_007) 

The 2 th matrix
[[    0    10 99999     6     7 99999 99999     1 99999]
 [   11     0    11 99997     4     7     9 99999     6]
 [   14    -2     0 99997     7     5    12 99997     4]
 [   -3 99996 99996     0    -1 99996     4    -2     1]
 [99996     3 99999 99997     0    10 99999 99999     9]
 [99996     2     4 99997 99997     0 99999 99999    13]
 [   -5     3     5    -2 99997 99997     0 99997    -1]
 [    2 99997 99999     5 99997 99999 99999     0     6]
 [    5     1     8     1    -2 99997     3     6     0]]
The 4 th matrix
[[    0    10    21     6     5    17    10     1     7]
 [    4     0    11     7     4     7     9    12     6]
 [    7    -2     0     5     2     5     7    10     4]
 [   -3     2     9     0    -1     9     4    -2     1]
 [   14     3    14    10     0    10    12    15     9]
 [   13     2     4    14     6     0    11    19     8]
 [   -5     0     5    -2    -3    10     0    -4    -1]
 [    2     7    14     5     4 99999     9     0     6